lesson03 - modules
wizelineacademy/terraform-academy pull request #13
Opened 2019-05-03 17:01 UTC by sortigoza

adds: lesson03 - modules

2019-05-03 17:19 UTC, chitopunk requested changes

2019-05-03 17:19 UTC, chitopunk commented on lesson03/environments/terraform-dev.tfvars
> +  project = "academy-user-N"
parametrized

2019-05-03 17:19 UTC, chitopunk commented on lesson03/environments/terraform-prod.tfvars
> +  appname = "academy-user-N"
same here

2019-05-03 17:19 UTC, chitopunk commented on lesson03/environments/terraform-prod.tfvars
> +  project = "academy-user-N"
here parameter

2019-05-03 17:54 UTC, sortigoza commented
parametrized in https://github.com/wizelineacademy/terraform-academy/pull/13/files#diff-c0f726443ff58cba193c56b9b72afb0cR35

2019-05-03 17:54 UTC, sortigoza commented on lesson03/environments/terraform-prod.tfvars
> +  project = "academy-user-N"
see comment below

2019-05-03 17:54 UTC, sortigoza commented on lesson03/environments/terraform-prod.tfvars
> +  appname = "academy-user-N"
see comment below

2019-05-03 17:54 UTC, sortigoza commented on lesson03/environments/terraform-dev.tfvars
> +  project = "academy-user-N"
see comment below

2019-05-06 21:44 UTC, dancortes94 approved these changes
LGTM

2019-05-07 16:50 UTC, chitopunk approved these changes
LGTM

2019-05-07 16:50 UTC, merged