This allows to chage images in a parametrized way for lesson02
wizelineacademy/terraform-academy pull request #40
Opened 2019-10-11 19:22 UTC by chitopunk

Uses parametrized docker images, use name in asg to detect changes and redeploy

2019-10-11 20:50 UTC, charlycastro commented
nice, looks cleaner

2019-10-11 20:50 UTC, charlycastro approved these changes
👍

2019-10-11 20:52 UTC, eloyvega approved these changes
LGTM 🚢

2019-10-16 14:44 UTC, estebancrw requested changes
Great work! The only blocking issue is the question about the ASG name, the others are NBD

2019-10-16 14:44 UTC, estebancrw commented on lesson02/userdata.sh
> +docker run -d -p 80:80 --restart=always ${docker_image}:${docker_tag}
Nice! 👍 
non-related to this PR, since `userdata.sh` is a template file, would be nice adding a `.tpl` at the end of the file name

2019-10-16 14:44 UTC, estebancrw commented on lesson02/userdata.sh
> +#Run the nginx
Since this may no longer be nginx, should we modify the comment to something similar to:
"# Run the Docker image"

2019-10-16 14:44 UTC, estebancrw commented on slides/lesson2/solution/main.tf
> +  name                 = aws_launch_configuration.lc.name
My understanding is that adding `appversion` to the ASG name is a trick. This makes Terraform create a new ASG each time we update our version, making AWS create new EC2 instances that have our changes.
With this new change, if we update our `appversion` are the EC2 instances also updated or do they stay the same until an EC2 is restarted?

2019-10-16 14:44 UTC, estebancrw commented on lesson02/data_sources.tf
> +    ENVIRONMENT  = var.env
I think we're not using `ENVIRONMENT` in our `userdata.sh`. Should we remove this line?

2019-10-16 14:50 UTC, estebancrw approved these changes

2019-10-16 14:51 UTC, merged